<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '10',
    'typeid' => '0',
    'title' => '4月29日为“首都网络安全日”',
    'style' => '',
    'thumb' => '/uploadfile/2014/0628/20140628090026501.jpg',
    'keywords' => '首都 网络安全',
    'description' => 'Windows系统一般是每隔2 5至3年左右会更新一次，而在一年前，微软表示将加快更新速度，现在看来似乎已经做到了。',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=10&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1403960302',
    'updatetime' => '1403963161',
    'hitsid' => 'c-1-4',
    'views' => '5',
    'yesterdayviews' => '0',
    'dayviews' => '5',
    'weekviews' => '5',
    'monthviews' => '5',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '9',
    'typeid' => '0',
    'title' => '微软八月份或迎来Win8.1第二次更新',
    'style' => '',
    'thumb' => '/uploadfile/2014/0628/20140628084643879.jpg',
    'keywords' => '微软 Win8 更新',
    'description' => '[导读] Windows系统一般是每隔2 5至3年左右会更新一次，而在一年前，微软表示将加快更新速度，现在看来似乎已经做到了。',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1403959496',
    'updatetime' => '1403965881',
    'hitsid' => 'c-1-1',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '10',
    'typeid' => '0',
    'title' => 'Linux 平台七大桌面环境通览',
    'style' => '',
    'thumb' => '/uploadfile/2014/0628/20140628103917987.png',
    'keywords' => 'Linux 平台  桌面  环境',
    'description' => '通常的 Linux 发行版都使用 KDE 或者 GNOME 作为默认的桌面环境。它们都给用户提供了一个原始的并且有吸引力的桌面，并且内置了各式各样的多媒体软件、系统程序、游戏、实用程序。',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=10&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1403966162',
    'updatetime' => '1404316817',
    'hitsid' => 'c-1-7',
    'views' => '8',
    'yesterdayviews' => '2',
    'dayviews' => '2',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Web开发者的10个最好的云开发环境',
    'style' => '',
    'thumb' => '/uploadfile/2014/0628/20140628092721659.jpg',
    'keywords' => 'Web 开发者 云开发 环境',
    'description' => '在web开发人员中，基于云计算的开发环境正在快速地获得越来越多的人气 。 云开发环境是基于web的集成开发环境（IDE）。',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1403961905',
    'updatetime' => '1404012186',
    'hitsid' => 'c-1-6',
    'views' => '3',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '9',
    'typeid' => '0',
    'title' => '内向的亚裔程序员，如何在西方交到朋友？',
    'style' => '',
    'thumb' => '/uploadfile/2014/0629/20140629022416172.jpg',
    'keywords' => '亚裔 程序员 朋友',
    'description' => '不知道你有没有听说过编程忧郁症这个词，说是在开发者行列中，这样的程序员还是比较多，问题关键出在他们很少和人交流。',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1403979747',
    'updatetime' => '1404313121',
    'hitsid' => 'c-1-8',
    'views' => '14',
    'yesterdayviews' => '10',
    'dayviews' => '3',
    'weekviews' => '4',
    'monthviews' => '3',
  ),
  32 => 
  array (
    'id' => '32',
    'catid' => '9',
    'typeid' => '0',
    'title' => '马总，首富的感觉是咋样的？',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '     马云：谢谢大家，非常感谢大家这么远飞到美国，今天我为阿里巴巴这个团队，我们的合伙人，我们的客户特别骄傲，也特别感动。十五   ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=32',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1411190723',
    'updatetime' => '1411190858',
    'hitsid' => 'c-1-32',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  21 => 
  array (
    'id' => '21',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Android One能让谷歌一统江湖吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '     文 孙永杰当苹果iPhone6及iPhone6S近日成为业内热点话题之时，苹果在智能手机市场最大的对手谷歌却在大洋彼岸的印度，联合当地厂   ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=21',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1411190810',
    'updatetime' => '1411190858',
    'hitsid' => 'c-1-21',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '9',
    'typeid' => '0',
    'title' => '“网购后悔权”与“机动车撞人负全责”一样扯淡',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '     七日无理由退货，这事儿你怎么看?如果你是网络买家，肯定会拍手称快，因为这是维护自身权益的重要途径啊，至少买错东西不用再担   ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1411190811',
    'updatetime' => '1411190858',
    'hitsid' => 'c-1-22',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>