<?php
return array (
  7 => 
  array (
    'id' => '7',
    'catid' => '10',
    'typeid' => '0',
    'title' => 'Linux 平台七大桌面环境通览',
    'style' => '',
    'thumb' => '/uploadfile/2014/0628/20140628103917987.png',
    'keywords' => 'Linux 平台  桌面  环境',
    'description' => '通常的 Linux 发行版都使用 KDE 或者 GNOME 作为默认的桌面环境。它们都给用户提供了一个原始的并且有吸引力的桌面，并且内置了各式各样的多媒体软件、系统程序、游戏、实用程序。',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=10&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1403966162',
    'updatetime' => '1404316817',
    'hitsid' => 'c-1-7',
    'views' => '8',
    'yesterdayviews' => '2',
    'dayviews' => '2',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '10',
    'typeid' => '0',
    'title' => '4月29日为“首都网络安全日”',
    'style' => '',
    'thumb' => '/uploadfile/2014/0628/20140628090026501.jpg',
    'keywords' => '首都 网络安全',
    'description' => 'Windows系统一般是每隔2 5至3年左右会更新一次，而在一年前，微软表示将加快更新速度，现在看来似乎已经做到了。',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=10&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1403960302',
    'updatetime' => '1403963161',
    'hitsid' => 'c-1-4',
    'views' => '5',
    'yesterdayviews' => '0',
    'dayviews' => '5',
    'weekviews' => '5',
    'monthviews' => '5',
  ),
);
?>