<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '9',
    'typeid' => '0',
    'title' => '微软八月份或迎来Win8.1第二次更新',
    'style' => '',
    'thumb' => '/uploadfile/2014/0628/20140628084643879.jpg',
    'keywords' => '微软 Win8 更新',
    'description' => '[导读] Windows系统一般是每隔2 5至3年左右会更新一次，而在一年前，微软表示将加快更新速度，现在看来似乎已经做到了。',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1403959496',
    'updatetime' => '1403965881',
    'hitsid' => 'c-1-1',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Web开发者的10个最好的云开发环境',
    'style' => '',
    'thumb' => '/uploadfile/2014/0628/20140628092721659.jpg',
    'keywords' => 'Web 开发者 云开发 环境',
    'description' => '在web开发人员中，基于云计算的开发环境正在快速地获得越来越多的人气 。 云开发环境是基于web的集成开发环境（IDE）。',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1403961905',
    'updatetime' => '1404012186',
    'hitsid' => 'c-1-6',
    'views' => '3',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '9',
    'typeid' => '0',
    'title' => '内向的亚裔程序员，如何在西方交到朋友？',
    'style' => '',
    'thumb' => '/uploadfile/2014/0629/20140629022416172.jpg',
    'keywords' => '亚裔 程序员 朋友',
    'description' => '不知道你有没有听说过编程忧郁症这个词，说是在开发者行列中，这样的程序员还是比较多，问题关键出在他们很少和人交流。',
    'posids' => '1',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1403979747',
    'updatetime' => '1404313121',
    'hitsid' => 'c-1-8',
    'views' => '14',
    'yesterdayviews' => '10',
    'dayviews' => '3',
    'weekviews' => '4',
    'monthviews' => '3',
  ),
  26 => 
  array (
    'id' => '26',
    'catid' => '9',
    'typeid' => '0',
    'title' => '谁敢横刀立马，唯我1799',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '     当今影响力最大的三个科技大佬那就是小米雷军、魅族黄章、锤子老罗了，他们之间的斗争貌似三分天下，当魅族MX4的1799元的售价，   ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=26',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1411190813',
    'updatetime' => '1411190858',
    'hitsid' => 'c-1-26',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  25 => 
  array (
    'id' => '25',
    'catid' => '9',
    'typeid' => '0',
    'title' => '瓶颈已现，飞鱼科技面临IPO最后机会',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '     ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=25',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1411190812',
    'updatetime' => '1411190858',
    'hitsid' => 'c-1-25',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  24 => 
  array (
    'id' => '24',
    'catid' => '9',
    'typeid' => '0',
    'title' => '失去乔布斯的苹果真的江郎才尽了吗?',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '     文 张江健苹果刚刚发布了下一代智能手机iPhone 6及iPhone 6 Plus，没有期待中的无与伦比的绝世惊艳，只有更大的屏幕尺寸、更   ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=24',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1411190812',
    'updatetime' => '1411190858',
    'hitsid' => 'c-1-24',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '9',
    'typeid' => '0',
    'title' => '朋友圈代购屡禁不止根源何在？',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '     ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1411190811',
    'updatetime' => '1411190858',
    'hitsid' => 'c-1-23',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '9',
    'typeid' => '0',
    'title' => '“网购后悔权”与“机动车撞人负全责”一样扯淡',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '     七日无理由退货，这事儿你怎么看?如果你是网络买家，肯定会拍手称快，因为这是维护自身权益的重要途径啊，至少买错东西不用再担   ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1411190811',
    'updatetime' => '1411190858',
    'hitsid' => 'c-1-22',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  21 => 
  array (
    'id' => '21',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Android One能让谷歌一统江湖吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '     文 孙永杰当苹果iPhone6及iPhone6S近日成为业内热点话题之时，苹果在智能手机市场最大的对手谷歌却在大洋彼岸的印度，联合当地厂   ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=21',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1411190810',
    'updatetime' => '1411190858',
    'hitsid' => 'c-1-21',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  32 => 
  array (
    'id' => '32',
    'catid' => '9',
    'typeid' => '0',
    'title' => '马总，首富的感觉是咋样的？',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '     马云：谢谢大家，非常感谢大家这么远飞到美国，今天我为阿里巴巴这个团队，我们的合伙人，我们的客户特别骄傲，也特别感动。十五   ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=9&id=32',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1411190723',
    'updatetime' => '1411190858',
    'hitsid' => 'c-1-32',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>